/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    CurrentTechStack: typeof import('./src/components/CurrentTechStack.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/PresentationHeader.vue')['default']
    PresentationHeader: typeof import('./src/components/PresentationHeader.vue')['default']
    TopBarMenu: typeof import('./src/components/TopBarMenu.vue')['default']
  }
}
